const tests = [
  {
    id: 1,
    name: "Java",
    level: "Begginer",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/6b/f4/ec/6bf4ec1a131cc096b321b703a675a043.jpg",
    questions: [
      {
        prompt:
          "Which data type is used to create a variable that should store text?",
        optionA: "txt",
        optionB: "string",
        optionC: "myString",
        optionD: "String",
        answer: "optionB",
      },
      {
        prompt: "How do you create a variable with the numeric value 5?",
        optionA: "x=5",
        optionB: "int x=5",
        optionC: "num x=5",
        optionD: "float x=5",
        answer: "optionB",
      },
      {
        prompt: "How do you create a variable with the floating number 2.8?",
        optionA: "int x = 2.8f",
        optionB: "float x = 2.8f",
        optionC: "byte x = 2.8f",
        optionD: "x = 2.8f",
        answer: "optionB",
      },
      {
        prompt: "Which method can be used to find the length of a string?",
        optionA: "length()",
        optionB: "getLength()",
        optionC: "len()",
        optionD: "getSize()",
        answer: "optionA",
      },
      {
        prompt:
          "Which method can be used to return a string in upper case letters?",
        optionA: "upperCase()",
        optionB: "touppercase()",
        optionC: "toUpperCase()",
        optionD: "tuc()",
        answer: "optionC",
      },
    ],
  },
  {
    id: 2,
    name: "CSS",
    level: "Beginner",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/8f/b9/c2/8fb9c2588c373b98f09b6fff29c9fbb0.jpg",
    questions: [
      {
        prompt: "What does CSS stand for?",
        optionA: "cascading style sheets",
        optionB: "cascading style shoot",
        optionC: "corner style sheets",
        optionD: "cow style sheets",
        answer: "optionA",
      },
      {
        prompt:
          "Where in an HTML document is the correct place to refer to an external style sheet?",
        optionA: "in the body section",
        optionB: "at the head tag",
        optionC: "in the middle",
        optionD: "at the start",
        answer: "optionB",
      },
      {
        prompt: "Which HTML tag is used to define an internal style sheet?",
        optionA: "css",
        optionB: "script",
        optionC: "style",
        optionD: "div",
        answer: "optionC",
      },
      {
        prompt: "Which HTML attribute is used to define inline styles?",
        optionA: "font",
        optionB: "class",
        optionC: "styles",
        optionD: "style",
        answer: "optionD",
      },
      {
        prompt:
          "Which CSS property is used to change the text color of an element?",
        optionA: "color",
        optionB: "bgcolor",
        optionC: "fgcolor",
        optionD: "sgcolor",
        answer: "optionA",
      },
    ],
  },
  {
    id: 3,
    name: "HMTL",
    level: "Beginner",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/13/b1/12/13b1128f07efd143d91788e89fd47c4c.jpg",
    questions: [
      {
        prompt: "What does HTML stand for?",
        optionA: "Hyper text markup language",
        optionB: "Hyperlinks text markup language",
        optionC: "Home toll markup language",
        optionD: "All",
        answer: "optionA",
      },
      {
        prompt: "Who is making the Web standards?",
        optionA: "World wide web",
        optionB: "Google",
        optionC: "Microsoft",
        optionD: "All",
        answer: "optionA",
      },
      {
        prompt: "Choose the correct HTML element for the largest heading:",
        optionA: "head",
        optionB: "h1",
        optionC: "div",
        optionD: "img",
        answer: "optionB",
      },
      {
        prompt: "What is the correct HTML element for inserting a line break?",
        optionA: "lb",
        optionB: "break",
        optionC: "a",
        optionD: "br",
        answer: "optionD",
      },
      {
        prompt: "What is the correct HTML for creating a hyperlink?",
        optionA: "a",
        optionB: "a url",
        optionC: "a href",
        optionD: "all",
        answer: "optionC",
      },
    ],
  },
  {
    id: 4,
    name: "React JS",
    level: "Intermediate",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/63/03/d0/6303d0bacd87476a01fb4164df339397.jpg",
    questions: [
      {
        prompt: "What is the correct command to create a new React project?",
        optionA: "npm create-react-app myapp",
        optionB: "npx create-react-app myapp",
        optionC: "npm myapp",
        optionD: "npx myapp",
        answer: "optionB",
      },
      {
        prompt:
          "What command is used to start the React local development server?",
        optionA: "npm build",
        optionB: "npm run dev",
        optionC: "npx start",
        optionD: "npm start",
        answer: "optionD",
      },
      {
        prompt:
          "What is the default local host port that a React development server uses?",
        optionA: "8080",
        optionB: "5000",
        optionC: "3500",
        optionD: "3000",
        answer: "optionD",
      },
      {
        prompt: "What is the children prop?",
        optionA: "a property that lets you set an object as a property",
        optionB: "a property that adds child values to state",
        optionC: "a property that lets you pass data to child components",
        optionD: "a property that lets you nest components in other components",
        answer: "optionD",
      },
      {
        prompt: "Which keyword creates a constant in JavaScript?",
        optionA: "constant",
        optionB: "let",
        optionC: "var",
        optionD: "const",
        answer: "optionD",
      },
    ],
  },
  {
    id: 5,
    name: "Javascript",
    level: "Intermediate",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/de/84/1f/de841f59cc8d08339956ce0776608e42.jpg",
    questions: [
      {
        prompt: "Inside which HTML element do we put the JavaScript?",
        optionA: "script",
        optionB: "javascript",
        optionC: "js",
        optionD: "scripting",
        answer: "optionA",
      },
      {
        prompt: "Where is the correct place to insert a JavaScript?",
        optionA: "both the head and body",
        optionB: "the body section",
        optionC: "the head section",
        optionD: "at the end",
        answer: "optionD",
      },
      {
        prompt: "How do you call a function named myFunction?",
        optionA: "call myFunction()",
        optionB: "call function myFunction()",
        optionC: "myFunction()",
        optionD: "const function myFunction",
        answer: "optionC",
      },
      {
        prompt: "How to write an IF statement in JavaScript?",
        optionA: "if i==5 then",
        optionB: "if i=5",
        optionC: "if i=5 then",
        optionD: "if(i==5)",
        answer: "optionD",
      },
      {
        prompt: "How does a WHILE loop start?",
        optionA: "while(i <=10;i++)",
        optionB: "while i = 1 to 10",
        optionC: "while(i<=10)",
        optionD: "all",
        answer: "optionC",
      },
    ],
  },
  {
    id: 6,
    name: "SQL",
    level: "Advanced",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/3b/29/9d/3b299d7155d573b4f67c07de3c83a83c.jpg",
    questions: [
      {
        prompt: "What does SQL stand for?",
        optionA: "Structured Question Language",
        optionB: "Structured Query Language",
        optionC: "Strong Question Language",
        optionD: "Statistic Query Language",
        answer: "optionB",
      },
      {
        prompt: "Which SQL statement is used to extract data from database?",
        optionA: "GET",
        optionB: "OPEN",
        optionC: "SELECT",
        optionD: "EXTRACT",
        answer: "optionA",
      },
      {
        prompt: "Which SQL statement is used to update data from database?",
        optionA: "SAVE",
        optionB: "UPDATE",
        optionC: "MODIFY",
        optionD: "SAVE AS",
        answer: "optionB",
      },
      {
        prompt: "Which SQL statement is used to delete data from database?",
        optionA: "REMOVE",
        optionB: "COLLAPSE",
        optionC: "DELETE",
        optionD: "UPDATE",
        answer: "optionC",
      },
      {
        prompt: "Which SQL statement is used to insert new data in a database?",
        optionA: "ADD RECORD",
        optionB: "INSERT INTO",
        optionC: "INSERT NEW",
        optionD: "ADD NEW",
        answer: "optionB",
      },
    ],
  },
  {
    id: 7,
    name: "Python",
    level: "Advanced",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/30/73/b8/3073b83a620c9116a587d170c364b8eb.jpg",
    questions: [
      {
        prompt: "Which one is not a legal variable name?",
        optionA: "my-var",
        optionB: "Myvar",
        optionC: "_myvar",
        optionD: "my_var",
        answer: "optionB",
      },
      {
        prompt: "What is the correct file extension for Python files?",
        optionA: ".pt",
        optionB: ".pyth",
        optionC: ".py",
        optionD: ".pyt",
        answer: "optionC",
      },
      {
        prompt: "What is the correct way to create a function in Python?",
        optionA: "function myfunction():",
        optionB: "def myFunction():",
        optionC: "create myFunction():",
        optionD: "all",
        answer: "optionA",
      },
      {
        prompt:
          "Which method can be used to remove any whitespace from both the beginning and the end of a string?",
        optionA: "trim",
        optionB: "ptrim",
        optionC: "strip",
        optionD: "len",
        answer: "optionA",
      },
      {
        prompt:
          "Which method can be used to return a string in upper case letters?",
        optionA: "upperCase()",
        optionB: "upper()",
        optionC: "toUpperCase()",
        optionD: "uppercase()",
        answer: "optionC",
      },
    ],
  },
  {
    id: 8,
    name: "C++",
    level: "Advanced",
    tip: "quiz",
    img: "https://i.pinimg.com/564x/82/5e/6d/825e6dc069d682fc123c2a28f07b1b66.jpg",
    questions: [
      {
        prompt:
          "Which data type is used to create a variable that should store text?",
        optionA: "String",
        optionB: "Txt",
        optionC: "string",
        optionD: "myString",
        answer: "optionC",
      },
      {
        prompt: "How do you create a variable with the numeric value 5?",
        optionA: "num x = 5",
        optionB: "x = 5",
        optionC: "int x = 5",
        optionD: "double x = 5",
        answer: "optionC",
      },
      {
        prompt: "How do you create a variable with the floating number 2.8?",
        optionA: "int x = 2.8",
        optionB: "double x = 2.8",
        optionC: "byte x = 2.8",
        optionD: "x = 2.8",
        answer: "optionB",
      },
      {
        prompt: "Which header file lets us work with input and output objects?",
        optionA: "#include <inputstr>",
        optionB: "#include <iostream>",
        optionC: "#include <iosstring>",
        optionD: "#include <stream>",
        answer: "optionB",
      },
      {
        prompt: "Which keyword is used to create a class in C++?",
        optionA: "class()",
        optionB: "MyClass",
        optionC: "class",
        optionD: "className",
        answer: "optionC",
      },
    ],
  },
];

export default tests;
